const PIECES={white:{king:'♔',queen:'♕',rook:'♖',bishop:'♗',knight:'♘',pawn:'♙'},black:{king:'♚',queen:'♛',rook:'♜',bishop:'♝',knight:'♞',pawn:'♟'}};
const PIECE_VALUES={pawn:1,knight:3,bishop:3,rook:5,queen:9,king:0};
let board=[],selectedSquare=null,currentPlayer='white',gameOver=false,moveHistory=[],capturedPieces={white:[],black:[]},gameMode='pvp';
const chessBoard=document.getElementById('chessBoard'),turnDisplay=document.getElementById('turnDisplay'),checkDisplay=document.getElementById('checkDisplay'),message=document.getElementById('message'),gameModeSelector=document.getElementById('modeSelector'),gameArea=document.getElementById('gameArea');
function startGame(mode){gameMode=mode;gameModeSelector.style.display='none';gameArea.style.display='block';initBoard();renderBoard();}
document.getElementById('newGameBtn').addEventListener('click',()=>{gameArea.style.display='none';gameModeSelector.style.display='block';});
document.getElementById('undoBtn').addEventListener('click',undoMove);
document.getElementById('hintBtn').addEventListener('click',showHint);
function initBoard(){board=[[{piece:'rook',color:'black'},{piece:'knight',color:'black'},{piece:'bishop',color:'black'},{piece:'queen',color:'black'},{piece:'king',color:'black'},{piece:'bishop',color:'black'},{piece:'knight',color:'black'},{piece:'rook',color:'black'}],[{piece:'pawn',color:'black'},{piece:'pawn',color:'black'},{piece:'pawn',color:'black'},{piece:'pawn',color:'black'},{piece:'pawn',color:'black'},{piece:'pawn',color:'black'},{piece:'pawn',color:'black'},{piece:'pawn',color:'black'}],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[null,null,null,null,null,null,null,null],[{piece:'pawn',color:'white'},{piece:'pawn',color:'white'},{piece:'pawn',color:'white'},{piece:'pawn',color:'white'},{piece:'pawn',color:'white'},{piece:'pawn',color:'white'},{piece:'pawn',color:'white'},{piece:'pawn',color:'white'}],[{piece:'rook',color:'white'},{piece:'knight',color:'white'},{piece:'bishop',color:'white'},{piece:'queen',color:'white'},{piece:'king',color:'white'},{piece:'bishop',color:'white'},{piece:'knight',color:'white'},{piece:'rook',color:'white'}]];currentPlayer='white';gameOver=false;moveHistory=[];capturedPieces={white:[],black:[]};}
function renderBoard(){chessBoard.innerHTML='';for(let row=0;row<8;row++){for(let col=0;col<8;col++){const square=document.createElement('div');square.classList.add('square',(row+col)%2===0?'light':'dark');square.dataset.row=row;square.dataset.col=col;const piece=board[row][col];if(piece){const pieceEl=document.createElement('div');pieceEl.classList.add('piece');pieceEl.textContent=PIECES[piece.color][piece.piece];square.appendChild(pieceEl);}square.addEventListener('click',handleSquareClick);chessBoard.appendChild(square);}}updateDisplay();}
function handleSquareClick(e){if(gameOver||(gameMode!=='pvp'&&currentPlayer==='black'))return;const square=e.currentTarget;const row=parseInt(square.dataset.row);const col=parseInt(square.dataset.col);if(selectedSquare){if(isValidMove(selectedSquare.row,selectedSquare.col,row,col)){makeMove(selectedSquare.row,selectedSquare.col,row,col);selectedSquare=null;clearHighlights();if(!gameOver){currentPlayer=currentPlayer==='white'?'black':'white';updateDisplay();if(gameMode!=='pvp'&&currentPlayer==='black'){setTimeout(()=>makeAIMove(),500);}}}else{const piece=board[row][col];if(piece&&piece.color===currentPlayer){selectSquare(row,col);}else{clearHighlights();selectedSquare=null;}}}else{const piece=board[row][col];if(piece&&piece.color===currentPlayer){selectSquare(row,col);}}}
function selectSquare(row,col){clearHighlights();selectedSquare={row,col};document.querySelectorAll('.square')[row*8+col].classList.add('selected');highlightValidMoves(row,col);}
function highlightValidMoves(row,col){for(let r=0;r<8;r++){for(let c=0;c<8;c++){if(isValidMove(row,col,r,c)){const square=document.querySelector(`[data-row="${r}"][data-col="${c}"]`);square.classList.add(board[r][c]?'capture-move':'valid-move');}}}}
function clearHighlights(){document.querySelectorAll('.square').forEach(s=>s.classList.remove('selected','valid-move','capture-move'));}
function isValidMove(fromRow,fromCol,toRow,toCol){if(fromRow===toRow&&fromCol===toCol)return false;if(toRow<0||toRow>7||toCol<0||toCol>7)return false;const piece=board[fromRow][fromCol];if(!piece)return false;const targetPiece=board[toRow][toCol];if(targetPiece&&targetPiece.color===piece.color)return false;return getPossibleMoves(fromRow,fromCol,piece).some(m=>m.row===toRow&&m.col===toCol);}
function getPossibleMoves(row,col,piece){const moves=[];switch(piece.piece){case'pawn':const dir=piece.color==='white'?-1:1;const start=piece.color==='white'?6:1;if(!board[row+dir]?.[col]){moves.push({row:row+dir,col});if(row===start&&!board[row+2*dir]?.[col])moves.push({row:row+2*dir,col});}[-1,1].forEach(dc=>{const target=board[row+dir]?.[col+dc];if(target&&target.color!==piece.color)moves.push({row:row+dir,col:col+dc});});break;case'rook':addLinearMoves(moves,row,col,piece,[[0,1],[0,-1],[1,0],[-1,0]]);break;case'bishop':addLinearMoves(moves,row,col,piece,[[1,1],[1,-1],[-1,1],[-1,-1]]);break;case'queen':addLinearMoves(moves,row,col,piece,[[0,1],[0,-1],[1,0],[-1,0],[1,1],[1,-1],[-1,1],[-1,-1]]);break;case'knight':[[2,1],[2,-1],[-2,1],[-2,-1],[1,2],[1,-2],[-1,2],[-1,-2]].forEach(([dr,dc])=>{const r=row+dr,c=col+dc;if(r>=0&&r<8&&c>=0&&c<8){const target=board[r][c];if(!target||target.color!==piece.color)moves.push({row:r,col:c});}});break;case'king':[[0,1],[0,-1],[1,0],[-1,0],[1,1],[1,-1],[-1,1],[-1,-1]].forEach(([dr,dc])=>{const r=row+dr,c=col+dc;if(r>=0&&r<8&&c>=0&&c<8){const target=board[r][c];if(!target||target.color!==piece.color)moves.push({row:r,col:c});}});break;}return moves;}
function addLinearMoves(moves,row,col,piece,directions){directions.forEach(([dr,dc])=>{let r=row+dr,c=col+dc;while(r>=0&&r<8&&c>=0&&c<8){const target=board[r][c];if(target){if(target.color!==piece.color)moves.push({row:r,col:c});break;}moves.push({row:r,col:c});r+=dr;c+=dc;}});}
function makeMove(fromRow,fromCol,toRow,toCol){const piece=board[fromRow][fromCol];const captured=board[toRow][toCol];moveHistory.push({from:{row:fromRow,col:fromCol},to:{row:toRow,col:toCol},piece:JSON.parse(JSON.stringify(piece)),captured:captured?JSON.parse(JSON.stringify(captured)):null});if(captured){capturedPieces[currentPlayer].push(PIECES[captured.color][captured.piece]);updateCapturedDisplay();}board[toRow][toCol]=piece;board[fromRow][fromCol]=null;if(piece.piece==='pawn'&&(toRow===0||toRow===7)){board[toRow][toCol]={piece:'queen',color:piece.color};}if(captured&&captured.piece==='king'){gameOver=true;const winner=(gameMode!=='pvp'&&currentPlayer==='black')?'🤖 AI':currentPlayer.charAt(0).toUpperCase()+currentPlayer.slice(1);message.textContent=`${winner} wins!`;message.className='message success';}renderBoard();}
function undoMove(){if(moveHistory.length===0)return;const last=moveHistory.pop();board[last.from.row][last.from.col]=last.piece;board[last.to.row][last.to.col]=last.captured;if(last.captured){capturedPieces[currentPlayer].pop();updateCapturedDisplay();}currentPlayer=currentPlayer==='white'?'black':'white';gameOver=false;message.textContent='';renderBoard();}
function makeAIMove(){if(gameOver)return;let move=null;if(gameMode==='ai-easy')move=getRandomAIMove();else if(gameMode==='ai-medium')move=getMediumAIMove();else if(gameMode==='ai-hard')move=getBestAIMove();if(move){makeMove(move.from.row,move.from.col,move.to.row,move.to.col);currentPlayer='white';updateDisplay();}}
function getRandomAIMove(){const moves=getAllPossibleMoves('black');return moves.length>0?moves[Math.floor(Math.random()*moves.length)]:null;}
function getMediumAIMove(){const moves=getAllPossibleMoves('black');if(moves.length===0)return null;const captures=moves.filter(m=>board[m.to.row][m.to.col]);return captures.length>0?captures[Math.floor(Math.random()*captures.length)]:moves[Math.floor(Math.random()*moves.length)];}
function getBestAIMove(){const moves=getAllPossibleMoves('black');if(moves.length===0)return null;let best=null,bestScore=-Infinity;moves.forEach(move=>{const score=evaluateChessMove(move);if(score>bestScore){bestScore=score;best=move;}});return best;}
function getAllPossibleMoves(color){const moves=[];for(let row=0;row<8;row++){for(let col=0;col<8;col++){const piece=board[row][col];if(piece&&piece.color===color){getPossibleMoves(row,col,piece).forEach(m=>{moves.push({from:{row,col},to:{row:m.row,col:m.col}});});}}}return moves;}
function evaluateChessMove(move){let score=0;const target=board[move.to.row][move.to.col];if(target)score+=PIECE_VALUES[target.piece]*10;const centerDist=Math.abs(move.to.row-3.5)+Math.abs(move.to.col-3.5);score+=(7-centerDist);const piece=board[move.from.row][move.from.col];if((piece.piece==='knight'||piece.piece==='bishop')&&move.from.row===0)score+=5;if(piece.piece==='pawn')score+=(7-move.to.row)*2;return score;}
function showHint(){if(gameOver)return;const pieces=[];for(let row=0;row<8;row++){for(let col=0;col<8;col++){const piece=board[row][col];if(piece&&piece.color===currentPlayer)pieces.push({row,col});}}if(pieces.length>0){const rnd=pieces[Math.floor(Math.random()*pieces.length)];const moves=getPossibleMoves(rnd.row,rnd.col,board[rnd.row][rnd.col]);if(moves.length>0){selectSquare(rnd.row,rnd.col);message.textContent=`Hint: Try moving this ${board[rnd.row][rnd.col].piece}`;message.className='message info';setTimeout(()=>message.textContent='',3000);}}}
function updateDisplay(){const player=(gameMode!=='pvp'&&currentPlayer==='black')?'🤖 AI':currentPlayer.charAt(0).toUpperCase()+currentPlayer.slice(1);turnDisplay.textContent=`${player}'s Turn`;turnDisplay.style.color=currentPlayer==='white'?'#333':'#764ba2';}
function updateCapturedDisplay(){document.getElementById('whiteCaptured').textContent=capturedPieces.white.join(' ');document.getElementById('blackCaptured').textContent=capturedPieces.black.join(' ');}
