const canvas=document.getElementById("canvas"),ctx=canvas.getContext("2d");
const tileSize=60;
let level=1,moves=0,player={x:1,y:1},boxes=[],goals=[],walls=[],history=[];
const levels={1:{player:{x:1,y:1},boxes:[{x:2,y:1}],goals:[{x:4,y:1}],walls:[{x:0,y:0},{x:1,y:0},{x:2,y:0},{x:3,y:0},{x:4,y:0},{x:5,y:0},{x:0,y:1},{x:5,y:1},{x:0,y:2},{x:5,y:2}]},2:{player:{x:1,y:1},boxes:[{x:2,y:2},{x:3,y:2}],goals:[{x:5,y:1},{x:5,y:2}],walls:[{x:0,y:0},{x:1,y:0},{x:2,y:0},{x:3,y:0},{x:4,y:0},{x:5,y:0},{x:6,y:0},{x:0,y:1},{x:6,y:1},{x:0,y:2},{x:6,y:2},{x:0,y:3},{x:6,y:3}]},3:{player:{x:1,y:1},boxes:[{x:2,y:2},{x:3,y:2},{x:2,y:3}],goals:[{x:6,y:1},{x:6,y:2},{x:6,y:3}],walls:[{x:0,y:0},{x:1,y:0},{x:2,y:0},{x:3,y:0},{x:4,y:0},{x:5,y:0},{x:6,y:0},{x:7,y:0},{x:0,y:1},{x:7,y:1},{x:0,y:2},{x:7,y:2},{x:0,y:3},{x:7,y:3},{x:0,y:4},{x:7,y:4}]}};
function startGame(l){level=l;document.getElementById("modeSelector").style.display="none";document.getElementById("gameArea").style.display="block";init();draw()}
function init(){moves=0;history=[];const lvl=levels[level];player={...lvl.player};boxes=lvl.boxes.map(b=>({...b}));goals=lvl.goals.map(g=>({...g}));walls=lvl.walls.map(w=>({...w}));updateUI()}
function draw(){ctx.fillStyle="#f0f0f0";ctx.fillRect(0,0,canvas.width,canvas.height);walls.forEach(w=>{ctx.fillStyle="#8B4513";ctx.fillRect(w.x*tileSize,w.y*tileSize,tileSize,tileSize)});goals.forEach(g=>{ctx.fillStyle="#90EE90";ctx.fillRect(g.x*tileSize,g.y*tileSize,tileSize,tileSize)});boxes.forEach(b=>{ctx.fillStyle=goals.some(g=>g.x===b.x&&g.y===b.y)?"#FFD700":"#CD853F";ctx.fillRect(b.x*tileSize+5,b.y*tileSize+5,tileSize-10,tileSize-10)});ctx.fillStyle="#FF6347";ctx.fillRect(player.x*tileSize+10,player.y*tileSize+10,tileSize-20,tileSize-20)}
function move(dx,dy){const newX=player.x+dx,newY=player.y+dy;if(walls.some(w=>w.x===newX&&w.y===newY))return;const box=boxes.find(b=>b.x===newX&&b.y===newY);if(box){const boxNewX=box.x+dx,boxNewY=box.y+dy;if(walls.some(w=>w.x===boxNewX&&w.y===boxNewY))return;if(boxes.some(b=>b.x===boxNewX&&b.y===boxNewY))return;history.push({player:{...player},boxes:boxes.map(b=>({...b}))});box.x=boxNewX;box.y=boxNewY;player.x=newX;player.y=newY;moves++;updateUI()}else{history.push({player:{...player},boxes:boxes.map(b=>({...b}))});player.x=newX;player.y=newY;moves++;updateUI()}draw();if(boxes.every(b=>goals.some(g=>g.x===b.x&&g.y===b.y)))alert("Level Complete! Moves: "+moves)}
function updateUI(){document.getElementById("moves").textContent=moves;document.getElementById("level").textContent=level}
document.addEventListener("keydown",e=>{if(e.key==="ArrowUp")move(0,-1);if(e.key==="ArrowDown")move(0,1);if(e.key==="ArrowLeft")move(-1,0);if(e.key==="ArrowRight")move(1,0)});
document.getElementById("undoBtn").addEventListener("click",()=>{if(history.length>0){const prev=history.pop();player=prev.player;boxes=prev.boxes;moves--;updateUI();draw()}});
document.getElementById("restartBtn").addEventListener("click",()=>{init();draw()});
document.getElementById("changeLevelBtn").addEventListener("click",()=>{document.getElementById("gameArea").style.display="none";document.getElementById("modeSelector").style.display="block"});